name: crawl mss

on:
  workflow_dispatch

jobs:
  send:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env
        run: |
          touch ./automation/discord-bot/fee-bot/.env
          echo "${{ secrets.CRAWL_ENV }}" > .env

      - name: run crawler
        run: |
          python crawler/save_to_dw.py